export type StaticPrettierOptionChoice = {
	value: string;
	description: string;
};

/**
 * A build-time snapshot of one Prettier option, generated by
 * scripts/generate-prettier-options.mjs from the pinned `prettier` package.
 *
 * This exists purely so the option vocabulary is present in the server-rendered
 * HTML. The live tool still loads Prettier from jsDelivr per selected version —
 * this snapshot never formats anything.
 */
export type StaticPrettierOption = {
	/** Prettier's camelCase option name — the literal term people search for. */
	key: string;
	category: string;
	type: string;
	description: string;
	/**
	 * Scalar for every option the UI renders. `plugins` is the sole array case
	 * and lives in IGNORED_OPTION_KEYS — the generator stays a dumb mirror of
	 * getSupportInfo() rather than knowing which options the UI hides.
	 */
	default: string | number | boolean | readonly string[] | null;
	choices: StaticPrettierOptionChoice[];
	/** e.g. `--print-width`, or `--no-semi` for booleans defaulting to true. */
	cliFlag: string;
	array?: boolean;
	range?: { start: number; end: number | null; step: number };
};
