import { PrettierOptionTypeEnum, PrettierOptionValidateEnum } from '@/common/enum/prettierOption';
import { PrettierOptionType } from '@/common/interface/PrettierOptionType';

/**
 * Database of all available Prettier configuration options.
 * Each option includes metadata for UI rendering, validation, and version history.
 */
const options: PrettierOptionType[] = [
	{
		name: 'Experimental Ternaries',
		since: '3.1.0',
		key: 'experimentalTernaries',
		description:
			'Uses a new ternary formatting style that aims to be more readable and consistent. This will likely become the default in future versions.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Experimental Operator Position',
		since: '3.5.0',
		key: 'experimentalOperatorPosition',
		description:
			'Controls where operators are placed when a line breaks (at the start or end of the line).',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['start', 'end'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Print Width',
		since: '0.0.0',
		key: 'printWidth',
		description:
			'Specifies the line length that the printer will wrap on. Note: This is not a hard limit, but a guideline.',
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: 'Tab Width',
		since: '0.0.0',
		key: 'tabWidth',
		description: 'Specifies the number of spaces per indentation-level.',
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: 'Tabs',
		since: '0.0.0',
		key: 'useTabs',
		description: 'Indent lines with tabs instead of spaces.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Semicolons',
		since: '0.0.0',
		key: 'semi',
		description: 'Print semicolons at the ends of statements.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Quotes',
		since: '0.0.0',
		key: 'singleQuote',
		description: 'Use single quotes instead of double quotes.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Quote Props',
		since: '1.17.0',
		key: 'quoteProps',
		description: 'Control when properties in objects are quoted.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['as-needed', 'consistent', 'preserve'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'JSX Quotes',
		since: '1.15.0',
		key: 'jsxSingleQuote',
		description: 'Use single quotes instead of double quotes in JSX.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Trailing Commas',
		since: '0.0.0',
		key: 'trailingComma',
		description:
			'Print trailing commas wherever possible in multi-line comma-separated syntactic structures.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['none', 'es5', 'all'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Bracket Spacing',
		since: '0.0.0',
		key: 'bracketSpacing',
		description: 'Print spaces between brackets in object literals.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Object Wrap',
		since: '3.5.0',
		key: 'objectWrap',
		description: 'Controls how object literals are wrapped when they exceed the print width.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['preserve', 'collapse'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Bracket Line',
		since: '2.4.0',
		key: 'bracketSameLine',
		description:
			'Put the > of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of the last line instead of being alone on the next line.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Arrow Function Parentheses',
		since: '1.9.0',
		key: 'arrowParens',
		description: 'Include parentheses around a sole arrow function parameter.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['avoid', 'always'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Range Start',
		since: '0.0.0',
		key: 'rangeStart',
		description: 'Format only a segment of a file, starting at a given character offset.',
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: 'Range End',
		since: '0.0.0',
		key: 'rangeEnd',
		description: 'Format only a segment of a file, ending at a given character offset (exclusive).',
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: 'Parser',
		since: '0.0.0',
		key: 'parser',
		description:
			'Specify which parser to use. Prettier automatically infers this from the file extension, but you can override it.',
		type: PrettierOptionTypeEnum.SELECT,
		options: [
			'babel',
			'babel-flow',
			'babel-ts',
			'flow',
			'typescript',
			'espree',
			'meriyah',
			'acorn',
			'css',
			'scss',
			'less',
			'json',
			'json5',
			'jsonc',
			'json-stringify',
			'graphql',
			'markdown',
			'mdx',
			'html',
			'vue',
			'angular',
			'lwc',
			'yaml',
		],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'File Path',
		since: '0.0.0',
		key: 'filePath',
		description: 'Specify the file name to use to infer which parser to use.',
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Require Pragma',
		since: '1.7.0',
		key: 'requirePragma',
		description:
			'Prettier can restrict itself to only format files that contain a special comment, called a pragma, at the top of the file.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Insert Pragma',
		since: '1.8.0',
		key: 'insertPragma',
		description:
			'Insert a special @format marker at the top of files specifying that the file has been formatted with Prettier.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Prose Wrap',
		since: '1.8.2',
		key: 'proseWrap',
		description:
			'How to wrap prose in markdown files (by default, Prettier wraps prose to the print width).',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['always', 'never', 'preserve'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'HTML Whitespace Sensitivity',
		since: '1.15.0',
		key: 'htmlWhitespaceSensitivity',
		description: 'Specify the global whitespace sensitivity for HTML files.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['css', 'strict', 'ignore'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Vue Indent Script and Style',
		since: '1.19.0',
		key: 'vueIndentScriptAndStyle',
		description: 'Whether or not to indent the code inside <script> and <style> tags in Vue files.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'End of Line',
		since: '1.15.0',
		key: 'endOfLine',
		description: 'Specify the line ending character to use.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['lf', 'crlf', 'cr', 'auto'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Embedded Language Formatting',
		since: '2.1.0',
		key: 'embeddedLanguageFormatting',
		description: 'Control whether Prettier formats quoted code embedded in the file.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ['auto', 'off'],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: 'Single Attribute Per Line',
		since: '2.6.0',
		key: 'singleAttributePerLine',
		description: 'Put each attribute on its own line of code in HTML, Vue, and JSX.',
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: 'Official Plugins',
		since: '0.0.0',
		key: 'plugins',
		description: 'The list of plugins to use by Prettier.',
		type: PrettierOptionTypeEnum.MULTISELECT,
		options: [
			'@prettier/plugin-php',
			'@prettier/plugin-pug',
			'@prettier/plugin-ruby',
			'@prettier/plugin-xml',
			'prettier-plugin-tailwindcss',
		],
		validate: PrettierOptionValidateEnum.STRING_ARRAY,
	},
];

export default options;
