import type { OptionArticle } from '@/common/interface/OptionArticle';

const article: OptionArticle = {
	tagline: 'lets a file opt itself out of formatting entirely',
	summary:
		"`checkIgnorePragma` makes Prettier honour a `@noprettier` marker in a file's first block comment and skip that file completely. It is the opt-out counterpart to `requirePragma`, and it is most useful for generated files whose paths are awkward to express in `.prettierignore`.",
	sections: [
		{
			heading: 'What the option does',
			blocks: [
				{
					kind: 'p',
					text: 'With `checkIgnorePragma: true`, Prettier inspects the first block comment of each file and skips any that contains `@noprettier`:',
				},
				{
					kind: 'code',
					code: '/**\n * @noprettier\n * Generated by scripts/build-schema.mjs — do not edit.\n */',
					caption: 'This file will not be formatted.',
				},
				{
					kind: 'p',
					text: 'The default is `false`, meaning the marker is ignored and the file is formatted like any other.',
				},
			],
		},
		{
			heading: 'Why it is better than .prettierignore for generated files',
			blocks: [
				{
					kind: 'p',
					text: 'A generator that emits files across several directories, or whose output paths depend on the input, is genuinely hard to express as a set of ignore globs. Keeping that pattern list in step with the generator is a maintenance task that nobody remembers until formatting breaks something.',
				},
				{
					kind: 'p',
					text: 'Emitting the marker from the generator itself moves the decision to where the knowledge is. Any file the generator writes announces its own status, and the ignore list never needs updating — the file and its exemption travel together, including when the output layout changes.',
				},
				{
					kind: 'p',
					text: 'It is also self-documenting. Someone opening the file sees immediately why it is not formatted, which an entry in `.prettierignore` does not tell them.',
				},
			],
		},
		{
			heading: 'How it differs from prettier-ignore',
			blocks: [
				{
					kind: 'ul',
					items: [
						'`@noprettier` with this option skips the entire file.',
						'`// prettier-ignore` skips the next node only, and needs no option — it is always honoured.',
						'`.prettierignore` skips by path, and is the right tool for whole directories such as `dist/` or `node_modules/`.',
					],
				},
				{
					kind: 'p',
					text: 'Reach for the narrowest of the three that solves your problem. A single stubborn matrix literal wants `// prettier-ignore`, not a whole-file exemption.',
				},
			],
		},
		{
			heading: 'Version note and common mistakes',
			blocks: [
				{
					kind: 'p',
					text: '`checkIgnorePragma` was added in Prettier 3.5. On earlier releases the marker has no effect at all, whatever your configuration says.',
				},
				{
					kind: 'ul',
					items: [
						'Adding `@noprettier` without enabling the option, so the file is formatted anyway.',
						'Using a line comment. It must be a block comment, and the first one in the file.',
						'Reaching for it when `// prettier-ignore` on a single node would do.',
						'Expecting it on Prettier 3.4 or older.',
					],
				},
			],
		},

		{
			heading: 'Choosing among the four ways to skip formatting',
			blocks: [
				{
					kind: 'p',
					text: 'Prettier offers four mechanisms and they are easy to confuse. They differ in scope and in where the decision is recorded:',
				},
				{
					kind: 'ul',
					items: [
						'`// prettier-ignore` — skips the next node. Always active, no configuration. Use it for a single hand-aligned matrix or ASCII table.',
						'`@noprettier` with `checkIgnorePragma` — skips the whole file, recorded in the file. Use it for generated output whose paths are hard to enumerate.',
						'`.prettierignore` — skips by path glob. Use it for whole directories such as `dist/` or vendored code.',
						'`requirePragma` — inverts the default so only marked files are formatted. Use it for gradual adoption, not for exclusions.',
					],
				},
				{
					kind: 'p',
					text: 'Prefer the narrowest mechanism that solves the problem. Reaching for a whole-file exemption when one node is the difficulty means the rest of the file quietly stops being formatted, and nobody notices until it has drifted.',
				},
			],
		},
		{
			heading: 'Emitting the marker from a generator',
			blocks: [
				{
					kind: 'p',
					text: 'The reason to prefer this over `.prettierignore` for generated code is that the generator already knows what it wrote. Emitting the header alongside the usual do-not-edit warning keeps the exemption and the file in one place:',
				},
				{
					kind: 'code',
					code: "const header = [\n  '/**',\n  ' * @noprettier',\n  ' * Generated by scripts/build-schema.mjs — do not edit.',\n  ' */',\n  '',\n].join('\\n');\n\nwriteFileSync(out, header + body);",
					caption: 'A generator writing its own exemption.',
				},
				{
					kind: 'p',
					text: 'Note the trade-off: a file exempted this way is also not checked by `prettier --check` in CI, so a hand-edit that breaks its formatting will not be caught. That is usually the intent for generated files, but it is worth being deliberate about.',
				},
			],
		},
	],
	faq: [
		{
			question: 'Why is my @noprettier comment being ignored?',
			answer:
				'Either `checkIgnorePragma` is not enabled — it defaults to `false` — or you are on a Prettier older than 3.5, where the option does not exist.',
		},
		{
			question: 'When should I use this instead of .prettierignore?',
			answer:
				'When the files are generated and their paths are hard to enumerate. Emit the marker from the generator and the exemption travels with the file.',
		},
	],
};

export default article;
